use_frameworks!
platform :ios, '10.0'


target 'BlockstackCoreApi_Example' do
  pod 'BlockstackCoreApi-iOS', :path => '../'

  target 'BlockstackCoreApi_Tests' do
    inherit! :search_paths

    
  end
end
